nem-toolchain/nem-toolchain

.editorconfig, .github/ISSUE_TEMPLATE.md, .gitignore, CONTRIBUTING.md, README.md
Add some general project info and files
=> Lack of contribution information

CONTRIBUTING.md
=> Wrong info about license header

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md
Change from `Constantine` to `Group of nem-toolchain project contributors`
=> Only the original author is a MIT license copyright holder

CONTRIBUTING.md, README.md
Clarify usage rules for github issues & gitter chat
=> Not obvious the difference between github issues and gitter chat

.gitignore, vag.go
Added simple generator example
Related to #8
=> Lack of account generator

vag.go, vag_test.go
=> Lack of unit tests for account gen

.editorconfig, .gitignore, CONTRIBUTING.md, LICENSE, README.md, cmd/nem/main.go, vanity.go, vanity_test.go
Rework it on base of https://carlosbecker.com/posts/golang-cli-apps/
=> Total project structure isn't complete

README.md
=> Wrong gitter badge icon

CONTRIBUTING.md, vanity.go, vanity_test.go
=> Wrong main package

.gitignore, .travis.yml
=> Lack of Mac OS X support for Travis

Makefile, cmd/nem/main.go, vanity.go, vanity_test.go
=> Lack of `cli` implementation

.travis.yaml
=> Lack of travis config 

README.md
=> Lack of circleCI badge

.travis.yml, doc.go, pkg/core/core.go, pkg/keypair/keypair.go, pkg/keypair/keypair_test.go, pkg/vanity/vanity.go
=> godoc isn't reference to any doc

doc.go, pkg/keypair/keypair.go
=> golink warning

README.md, cmd/nem/main.go, pkg/keypair/keypair.go, pkg/keypair/keypair_test.go
=> Cli application is broken

CONTRIBUTING.md, cmd/nem/main.go, pkg/keypair/keypair.go, pkg/keypair/keypair_test.go
=> Lack of address pretty formatting

CONTRIBUTING.md, README.md
=> Lack of cli examples in `README.md`

README.md
=> Minor typo in command example in `README.md`

doc.go
=> Very verbose `doc.go`

doc.go, pkg/keypair/keypair.go
=> Golint warning about blank import

pkg/keypair/keypair.go, pkg/keypair/keypair_test.go
=> Lack of pretty printing for address

pkg/keypair/keypair.go
=> Dirty "pretty string" implementation for address

cmd/nem/main.go, pkg/keypair/keypair.go, pkg/keypair/keypair_test.go
=> Lack of check for invalid address length

cmd/nem/main.go, pkg/keypair/keypair.go, pkg/keypair/keypair_test.go
Refactored address to use byte array
=> Lack of error handling for invalid address length

.gitignore, CONTRIBUTING.md, Makefile, VERSION, cmd/nem/main.go
Split into small separate methods.
=> Cli impl. is very monolith

cmd/nem/main.go
=> Golint warning: `BuildTime` should have comment

cmd/nem/main.go, pkg/keypair/keypair.go, pkg/keypair/keypair_test.go
=> There are another Golint warning

.circleci/config.yml
=> Invalid CircleCI config file

cmd/nem/main.go, pkg/keypair/keypair.go, pkg/vanity/vanity.go
Create a general logic template.
=> Lack of vanity address lookup

cmd/nem/main.go, pkg/vanity/vanity.go
Extract that logic into cli impl.
=> Vanity logic depends from goroutines

README.md, cmd/nem/main.go, doc.go, pkg/core/core.go, pkg/vanity/vanity.go, pkg/vanity/vanity_test.go
=> Multiple prefixes for vanity address search

README.md, cmd/nem/main.go
Added flag "-n"
Related to #61
=> Lack of funcitonality to specify amount of generated accounts

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SUPPORT.md, cmd/nem/main.go, pkg/vanity/vanity.go
=> Number of accounts to generate wrong option place

README.md
=> Lack of donation address

README.md, cmd/nem/main.go, doc.go, pkg/core/core.go
=> Wrong abbreviate for NEM blockchain

cmd/nem/main.go, pkg/domain/domain.go
Added functionality for calculation of account generation rate
Related to #51
=> Lack of functionality for calculation rate metric

Gopkg.lock, scripts/install, scripts/latest, scripts/latest.sh
=> Wrong shell scripts file extensions

scripts/install
=> Invalid archive format in install script

cmd/nem/main.go
=> Hide specified search complexity by default

.circleci/config.yml, .goreleaser.yml, Gopkg.lock, cmd/nem/main.go
=> Invlid environment variables for binary version

Makefile
=> Deploy failes due to gometalinter --update flag

Makefile
=> Useless compiler flags

Makefile
Reverts nem-toolchain/nem-toolchain#84
=> Revert "Useless compiler flags"

.circleci/config.yml, .goreleaser.yml, Gopkg.lock, Makefile, cmd/nem/main.go
=> Release DI script is over-complicated

.circleci/config.yml
=> goreleaser isn't triggered by releases tags

.goreleaser.yml
=> goreleaser unnecessary os replacement

.goreleaser.yml
=> goreleaser wrong artifacts names

.goreleaser.yml
=> fpm not present in $PATH for circleci

scripts/install
=> Downloaded binary file are not in PATH

scripts/install
Rewrite to install into local `bin` directory.
=> Install script extracts files into unknown temporary directory

README.md
=> Lack of main web site link

.circleci/config.yml, .github/ISSUE_TEMPLATE.md, .goreleaser.yml, CONTRIBUTING.md, scripts/install
=> There are a lot of useless release notes

.circleci/config.yml, CONTRIBUTING.md
=> circleci build fails

docs/000-introduction.md, docs/010-quick-strart.md, docs/020-environment.md, docs/999-links.md
=> Lack of `docs` section for web page 

Makefile
Added to `static` command to makefile
=> Lack of web page generation command 

.github/PULL_REQUEST_TEMPLATE.md, README.md
=> `How to start` section from `README.md` is wrong

cmd/nem/main.go, pkg/vanity/probability.go
Fixed, measure rate on all cpu cores simultaneously
=> Invalid routine for account rate calculation

README.md, docs/00-introduction.md, docs/03-commands.md, docs/04-guides.md
=> There are some typos on website

cmd/nem/main.go
=> Fix excessive method `showAccountEstimate` and zero number

CONTRIBUTING.md, Makefile, README.md, cmd/nem/main.go, docs/07-faq.md
=> Fix some minor documentation inconsistencies

.circleci/config.yml
Add a new excluded prefix - `Update`.
=> Fix release notes regexp pattern for circleci

README.md, cmd/nem/main.go
=> Fix version output for `go get`

README.md
=> Fix a link to the technical documentation

cmd/nem/main.go, pkg/keypair/keypair.go, pkg/vanity/probability.go
=> Fix command sub-method decomposition

Gopkg.lock, pkg/keypair/keypair_test.go
=> Invalid unit test for keypair generation

Gopkg.lock, README.md, docs/09-donations, docs/09-donations.md, pkg/keypair/keypair_test.go
=> Fix `Gopkg.lock`

cmd/nem/main.go
=> Lack of argument to specify workers count

cmd/nem/account.go
=> Lack of handling of stdin/out piping for `info` command

pkg/wallet/account/account.go, pkg/wallet/account/account_serialize.go, pkg/wallet/account/account_test.go, pkg/wallet/wallet.go, pkg/wallet/wallet_serialize.go
Refactored, separate domain from serialization
=> Invalid code structure of wallet package

pkg/wallet/account/account.go, pkg/wallet/account/encrypt.go, pkg/wallet/account/encrypt_test.go
=> Refactor wallet encrypt/decrypt

Dockerfile, README.md, docs/01-quick-start.md
Added lightweight image based on AlpineOS
Related to #152
----
=> Lack of image for nem-toolchain
